### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by chemxboy** [gilday/brightwheel-photos#14]
Getting a login failed when attempting to use this tool. I turned off 2-factor just in case, no change. I was able to verify the API still works while logged into the browser and viewing api results there. Is there any other things that need to be done when using the script?

**Comment by bhuber2010** [comment]
updating headers to the below fixes it

`headers = {
        "X-Client-Name": "web",
        "X-Client-Version": "213",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "User-Agent": "vscode-restclient"
    }`

**Comment by gilday** [comment]
> updating headers to the below fixes it. I think the user agent is the key one. Guessing Brightwheel decided to block generic python requests.
> 
> 
> 
> `headers = {
> 
>         "X-Client-Name": "web",
> 
>         "X-Client-Version": "213",
> 
>         "Content-Type": "application/json",
> 
>         "Accept": "application/json",
> 
>         "User-Agent": "vscode-restclient"
> 
>     }`

lgtm. I'll take a PR if you've got the time 🙏🏻.

**Comment by gilday** [comment]
This issue seems to be resolved.
